chance_constraint: 0.005
coVarX: 0.0001
coVarY: 0.0001
end_location:
- 1
- 1
- 0
- 0
environment: '[data_generator/psulu/config/newEnvi.yaml]'
max_control: 1
max_velocity: 2
start_location:
- 0
- 0
- 0
- 0
waypoints: 19
